name: CI

on: 
  push:
    branches: "addon"
  workflow_dispatch:

jobs:
  - name: Godot Asset Lib
    # You may pin to the exact commit or the version.
    # uses: deep-entertainment/godot-asset-lib-action@81addbb4db62199a69e4aa5535741a8928d6abb6
    uses: deep-entertainment/godot-asset-lib-action@v0.4.0
    with:
      # Godot asset lib username
      username: expressobits
      # Godot asset lib password
      password: {{ secrets.GODOT_ASSET_LIB_PASSWORD }}
      # ID of the asset in the asset store
      assetId: 1650
      # Path to asset template file
      assetTemplate: # default is .asset-template.json.hb
      # Godot asset lib base url
      baseUrl: # default is https://godotengine.org/asset-library/api
      # If your Godot asset library user has moderation features, you can directly approve the changes.
      approveDirectly: # default is false
